name: Deploy Frontend (EC2)

on:
  push:
    branches: [ aws-frontend-pipeline ]
    paths:
      - 'src/**'
      - 'index.html'
      - 'package.json'
      - 'vite.config.ts'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'

      - name: Install & Build
        working-directory: .
        env:
          VITE_API_BASE: ${{ secrets.FRONTEND_API_BASE }}
        run: |
          npm i
          npm run dev

      - name: Upload build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/home/ubuntu/srms/frontend/releases/tmp"
          overwrite: true

      - name: Publish on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            /home/ubuntu/srms/frontend/scripts/publish.sh "/home/ubuntu/srms/frontend/releases/tmp"